### ISSUE TITLE
Problem in project implementation

### ISSUE THREAD

**Issue by Rasool-deldar** [tmg0/unplugin-oxlint#90]
Hello, don't worry, I installed your package and encountered the following problem, how should I solve this problem?

```node
λ bun run dev
$ vite
Debugger attached.
Waiting for the debugger to disconnect...
project_path\node_modules\eslint\lib\eslint\eslint.js:349
            error = new Error("Could not find config file.");
                    ^

Error: Could not find config file.
    at locateConfigFileToUse (project_path\node_modules\eslint\lib\eslint\eslint.js:349:21)
    at async calculateConfigArray (project_path\node_modules\eslint\lib\eslint\eslint.js:385:49)
    at async ESLint.lintFiles (project_path\node_modules\eslint\lib\eslint\eslint.js:815:25)
    at async runESLintCommand (file:///project_path/node_modules/unplugin-oxlint/dist/chunk-V5M2YQO7.js:177:19)
    at async Promise.all (index 1)
    at async runLintCommand (file:///project_path/node_modules/unplugin-oxlint/dist/chunk-V5M2YQO7.js:206:19)
    at async Object.setup (file:///project_path/node_modules/unplugin-oxlint/dist/chunk-V5M2YQO7.js:251:7) {
  messageTemplate: 'config-file-missing'
}

Node.js v20.13.1
error: script "dev" exited with code 1
```

**Comment by tmg0** [comment]
Thank you for your question and for using this project!

But I could not reproduce the error you provided on my local environment. If possible please provide a minimal reproducible repository.

I noticed that you are using `Vite` for bundling, so I have created an example based on `Vite` + `Vue` on [StackBlitz](https://stackblitz.com/edit/vitejs-vite-hyzrfm?file=vite.config.ts) hope this can help you. And you can also directly modify the example.

**Comment by Rasool-deldar** [comment]
Thank you very much, my problem is solved
